import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const sourceRoot = dirname(fileURLToPath(import.meta.url));
export const defaultSiteUrl = 'https://echoesmusic.app/';

export function normalizeSiteUrl(value = defaultSiteUrl) {
  const url = new URL(value);
  if (!['https:', 'http:'].includes(url.protocol) || url.username || url.password || url.search || url.hash) {
    throw new Error('SITE_URL must be an HTTP(S) URL without credentials, query parameters or fragments.');
  }
  if (/\.[a-z0-9]+$/i.test(url.pathname) || /%2f|%5c/i.test(url.pathname)) {
    throw new Error('SITE_URL must point to a site directory, such as https://echoesmusic.app/.');
  }
  url.pathname = url.pathname.replace(/\/+$/, '') + '/';
  return url;
}

const escapeMarkup = (value) => String(value).replace(/[&<>"']/g, (character) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
})[character]);
const decodeMarkup = (value) => value.replace(/&(amp|lt|gt|quot|#39);/g, (_, entity) => ({
  amp: '&', lt: '<', gt: '>', quot: '"', '#39': "'",
})[entity]);
const locales = [
  { language: 'zh-CN', path: '', locale: 'zh_CN', otherLocale: 'en_US', imageAlt: 'Echoes 音乐播放器：音乐流与沉浸播放器真实界面' },
  { language: 'en', path: 'en/', locale: 'en_US', otherLocale: 'zh_CN', imageAlt: 'Echoes music player: music library and now playing screens, shown in Chinese' },
];

function addSeo(html, language, siteUrl) {
  const title = decodeMarkup(html.match(/<title>([^<]+)<\/title>/i)?.[1] || 'Echoes');
  const descriptionMatch = html.match(/<meta\s+name="description"\s+content="([^"]*)"\s*\/?\s*>/i);
  if (!descriptionMatch) throw new Error(`Missing description in ${language.path || '/'}index.html`);
  const description = decodeMarkup(descriptionMatch[1]);
  const pageUrl = new URL(language.path, siteUrl).href;
  const socialImage = new URL('assets/social-card.png', siteUrl).href;
  const graph = {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'WebSite', '@id': `${siteUrl.href}#website`, url: siteUrl.href, name: 'Echoes', inLanguage: ['zh-CN', 'en'] },
      {
        '@type': 'WebPage', '@id': `${pageUrl}#webpage`, url: pageUrl, name: title, description,
        inLanguage: language.language, isPartOf: { '@id': `${siteUrl.href}#website` },
        mainEntity: { '@id': `${siteUrl.href}#app` },
        primaryImageOfPage: { '@type': 'ImageObject', url: socialImage, width: 1200, height: 630 },
      },
      {
        '@type': 'SoftwareApplication', '@id': `${siteUrl.href}#app`, name: 'Echoes',
        applicationCategory: 'MultimediaApplication', operatingSystem: 'Android',
        description, url: pageUrl, isAccessibleForFree: true,
        license: 'https://opensource.org/license/mit/',
        downloadUrl: 'https://github.com/Azincc/echo/releases/latest',
        softwareHelp: 'https://github.com/Azincc/echo/blob/main/gitbook/README.md',
        screenshot: ['music-home.png', 'full-player.png', 'lyrics-view.png', 'library-home.png']
          .map((file) => new URL(`assets/${file}`, siteUrl).href),
      },
    ],
  };
  const seo = [
    '<!-- SEO is generated by build.mjs from SITE_URL and the localized page content. -->',
    `<link rel="canonical" href="${escapeMarkup(pageUrl)}">`,
    ...locales.map((item) => `<link rel="alternate" hreflang="${item.language}" href="${escapeMarkup(new URL(item.path, siteUrl).href)}">`),
    `<link rel="alternate" hreflang="x-default" href="${escapeMarkup(siteUrl.href)}">`,
    '<meta name="robots" content="index, follow, max-image-preview:large">',
    '<meta property="og:type" content="website">',
    '<meta property="og:site_name" content="Echoes">',
    `<meta property="og:locale" content="${language.locale}">`,
    `<meta property="og:locale:alternate" content="${language.otherLocale}">`,
    `<meta property="og:title" content="${escapeMarkup(title)}">`,
    `<meta property="og:description" content="${escapeMarkup(description)}">`,
    `<meta property="og:url" content="${escapeMarkup(pageUrl)}">`,
    `<meta property="og:image" content="${escapeMarkup(socialImage)}">`,
    '<meta property="og:image:type" content="image/png">',
    '<meta property="og:image:width" content="1200">',
    '<meta property="og:image:height" content="630">',
    `<meta property="og:image:alt" content="${escapeMarkup(language.imageAlt)}">`,
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${escapeMarkup(title)}">`,
    `<meta name="twitter:description" content="${escapeMarkup(description)}">`,
    `<meta name="twitter:image" content="${escapeMarkup(socialImage)}">`,
    `<meta name="twitter:image:alt" content="${escapeMarkup(language.imageAlt)}">`,
    `<script type="application/ld+json">${JSON.stringify(graph).replace(/</g, '\\u003c')}</script>`,
  ].join('\n  ');
  // Remove source social metadata to avoid duplicate or conflicting URL/locale values.
  return html.replace(/\s*<meta\b[^>]*(?:property="og:[^"]+"|name="twitter:[^"]+")[^>]*>/gi, '')
    .replace('</head>', `  ${seo}\n</head>`);
}

function sitemap(siteUrl) {
  const links = locales.map((item) => ({ ...item, url: new URL(item.path, siteUrl).href }));
  const alternatives = [...links, { language: 'x-default', url: siteUrl.href }]
    .map((item) => `    <xhtml:link rel="alternate" hreflang="${item.language}" href="${escapeMarkup(item.url)}"/>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${links.map((item) => `  <url>\n    <loc>${escapeMarkup(item.url)}</loc>\n${alternatives}\n  </url>`).join('\n')}\n</urlset>\n`;
}

function notFound(siteUrl) {
  const home = escapeMarkup(siteUrl.pathname);
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><meta name="theme-color" content="#0C0F12"><title>页面未找到 · Page not found — Echoes</title><link rel="icon" href="${home}assets/logo.png"><link rel="stylesheet" href="${home}styles.css"></head>
<body><main class="section shell" id="main"><p>404</p><h1>这里还没有回响。</h1><p class="hero-description">页面可能已移动，回到首页继续探索。</p><div lang="en"><h2>Page not found.</h2><p class="hero-description">This page may have moved. Find your way back to Echoes.</p></div><div class="hero-actions"><a class="button button-primary" href="${home}">返回中文首页</a><a class="text-link" href="${home}en/" lang="en" hreflang="en">English homepage</a></div></main></body></html>\n`;
}

export async function buildSite(value = process.env.SITE_URL || defaultSiteUrl) {
  const siteUrl = normalizeSiteUrl(value);
  const pages = await Promise.all(locales.map(async (language) => ({
    language, html: addSeo(await readFile(join(sourceRoot, language.path, 'index.html'), 'utf8'), language, siteUrl),
  })));
  const output = resolve(sourceRoot, 'dist');
  // This build owns exactly website/dist; never remove arbitrary caller-supplied paths.
  if (dirname(output) !== sourceRoot || output !== join(sourceRoot, 'dist')) throw new Error('Invalid output directory');
  await rm(output, { recursive: true, force: true });
  await mkdir(join(output, 'en'), { recursive: true });
  await Promise.all([
    ...pages.map(({ language, html }) => writeFile(join(output, language.path, 'index.html'), html)),
    ...['styles.css', 'script.js', '_headers'].map((file) => cp(join(sourceRoot, file), join(output, file))),
    cp(join(sourceRoot, 'assets'), join(output, 'assets'), { recursive: true }),
    writeFile(join(output, 'robots.txt'), `User-agent: *\nAllow: /\n\nSitemap: ${new URL('sitemap.xml', siteUrl).href}\n`),
    writeFile(join(output, 'sitemap.xml'), sitemap(siteUrl)),
    writeFile(join(output, '404.html'), notFound(siteUrl)),
    writeFile(join(output, '_redirects'), [
      '# Explicit document URLs use the same canonical routes as the locale metadata.',
      `${siteUrl.pathname}index.html ${siteUrl.pathname} 301`,
      `${siteUrl.pathname}en/index.html ${siteUrl.pathname}en/ 301`,
      `${siteUrl.pathname}en ${siteUrl.pathname}en/ 301`,
      '',
    ].join('\n')),
  ]);
  return { output, siteUrl: siteUrl.href };
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  const result = await buildSite();
  console.log(`Built website/dist for ${result.siteUrl}`);
}
